### ISSUE TITLE
Cannot infer type parameter T in fun<T,U> DeserializedResult....a

### ISSUE THREAD

**Issue by solusoftek** [kittinunf/Forge#17]
Using your code example,  i get this message, recently update  intellij to version 3.1.2, checking arround core.JSON class has Array but no list Type, the full message says: "none of the following substitutions receiver: DeserializedResult<(List<DeserializedResult<Dog>>) ->User> arguments:(DeserializedResult<List<DeserializedResult<Dog>>>) 
can be applied to 
receiver:DeserailizedResult<(List<Dog>?) ->User> arguments:(DeserializedResult<List<DeserializedResult<Dog>>)
this happen on this line  apply(json.maybeList("dogs", dogDeserializer))

**Comment by Firenox89** [comment]
Same for me using Android Studio 3.1.3, Kotlin Plugin 1.30 (also with 1.50)
this:
```
data class Dog(val name: String, val breed: String, val male: Boolean)
data class UserWithDogs(val email: String, val dogs: List<Dog>?, val phone: String)

fun dogDeserializer(json: JSON) =
    ::Dog.create.
            map(json at "name").
            apply(json at "breed").
            apply(json at "is_male")

val userWithDogDeserializer = { j: JSON ->
    ::UserWithDogs.create.
            map(j at "email").
            apply(j.list<Dog>("dogs", ::dogDeserializer)).
            apply(j at "phone")

}
```
results in this:

```
SomeClass.kt: (56, 13): Type inference failed: Cannot infer type parameter T in fun <T, U> DeserializedResult<(T) -> U>.apply(deserializedResult: DeserializedResult<T>): DeserializedResult<U>
None of the following substitutions
receiver: DeserializedResult<(List<DeserializedResult<Dog>>) -> (String) -> UserWithDogs>  arguments: (DeserializedResult<List<DeserializedResult<Dog>>>)
receiver: DeserializedResult<(List<Dog>?) -> (String) -> UserWithDogs>  arguments: (DeserializedResult<@ParameterName List<Dog>?>)
can be applied to
receiver: DeserializedResult<(List<Dog>?) -> (String) -> UserWithDogs>  arguments: (DeserializedResult<List<DeserializedResult<Dog>>>)

```

**Comment by Firenox89** [comment]
Actually this is fixed in the github version.
But the 0.3.0 still has it, time for a new release mate.

**Comment by kihaki** [comment]
Is this project still alive? Last release was over a year ago

**Comment by kittinunf** [comment]
Ah ... sorry I have been putting my focus somewhere else for a while. I will release new version!!

**Comment by kittinunf** [comment]
I released a new version!! Sorry for the wait guys!
