### ISSUE TITLE
Any reason why the Currying starts with Function2 instead of Function1?

### ISSUE THREAD

**Issue by janjaali** [kittinunf/Forge#24]
Actually this is not an issue, but unfortunately I found no other place to ask. 

Attempting to write a deserializer for a data-class holding only one field e.g. `data class Pet(val name: String)` I was struggling to find a matching Currying i.e. create function since it seems that the Currying starts with Function2.

code: https://github.com/kittinunf/Forge/blob/223e0a9fb05b20eb16bac38d5d246882f9eb271e/forge/src/main/kotlin/com/github/kittinunf/forge/util/Currying.kt#L3

**Comment by kittinunf** [comment]
Yes, you are right. I think for 1-field data class you can just use a constructor to instantiate? 😄 I guess I didn't cover them because I don't think we need something more than just a constructor.

Something like

``` kotlin
val fooDeserializer = { j: JSON ->
  Foo(j at name)
}
```

What do you think?

**Comment by janjaali** [comment]
Yes you are right, came up with the same solution, but was a bit surprisingly for me as a newbie. Do you mind if I try to create a PR for that or do you prefer the existing API? If not, please feel free to close this issue :)

**Comment by janjaali** [comment]
I think this little change #25 would be beneficial for the consistency of the existing API :)

**Comment by kittinunf** [comment]
Sure, I am happy to accept #25 :)
