### ISSUE TITLE
example cannot run at README.md?

### ISSUE THREAD

**Issue by shizhaojingszj** [kittinunf/Forge#33]
I just copy-and-paste the snippet to IDEA64, then this part :

```
import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.result.Result
import com.github.kittinunf.forge.core.JSON

// ...

::User.create.

// ...

```

gives me:

```
Unresolved reference: create
```

What am I missing? Thanks a lot.

**Comment by kittinunf** [comment]
It is actually here https://github.com/kittinunf/Forge/blob/cafa795687e1ce77919503ccb938bb81701a22dc/forge/src/main/kotlin/com/github/kittinunf/forge/util/Currying.kt#L7

Can you see whether you have the correct import or not?

**Comment by kittinunf** [comment]
Close as it has no updated.
